package com.example

import android.content.Context
import android.util.Log
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.util.zip.ZipInputStream

object LocalLatexCompiler {

    fun compile(context: Context, source: String, logBuilder: StringBuilder): File {
        logBuilder.append("[INFO] Starting true offline compilation using native Tectonic engine...\n")
        
        val workDir = context.cacheDir
        val sourceFile = File(workDir, "document.tex")
        val pdfFile = File(workDir, "document.pdf")
        
        // Clean up old pdf
        if (pdfFile.exists()) {
            pdfFile.delete()
        }

        // Write the source tex file
        sourceFile.writeText(source, Charsets.UTF_8)
        logBuilder.append("[INFO] Wrote document.tex to local cache.\n")

        // Extract the pre-bundled offline LaTeX bundle (flat directory with all .tex, .cls, .tfm, .otf, .fmt files)
        // This bundle was generated from a real Tectonic cache and contains everything needed for offline compilation.
        val bundleDir = File(workDir, "tectonic_bundle")
        if (!bundleDir.exists()) {
            logBuilder.append("[INFO] Extracting offline LaTeX bundle (first run only)...\n")
            try {
                bundleDir.mkdirs()
                context.assets.open("tectonic_bundle.zip").use { input ->
                    ZipInputStream(input).use { zis ->
                        var entry = zis.nextEntry
                        while (entry != null) {
                            val file = File(bundleDir, entry.name)
                            if (entry.isDirectory) {
                                file.mkdirs()
                            } else {
                                file.parentFile?.mkdirs()
                                file.outputStream().use { zis.copyTo(it) }
                            }
                            entry = zis.nextEntry
                        }
                    }
                }
                logBuilder.append("[INFO] Bundle extracted successfully!\n")
            } catch (e: Exception) {
                logBuilder.append("[ERROR] Failed to extract bundle: ${e.localizedMessage}\n")
                throw Exception("Failed to extract offline LaTeX bundle: ${e.localizedMessage}")
            }
        }
        
        // Locate the Tectonic binary in the native libraries directory
        val nativeLibraryDir = context.applicationInfo.nativeLibraryDir
        val tectonicBinary = File(nativeLibraryDir, "libtectonic.so")
        
        if (!tectonicBinary.exists()) {
            throw Exception("Tectonic binary not found in native library directory at ${tectonicBinary.absolutePath}")
        }
        
        logBuilder.append("[INFO] Located executable Tectonic engine at ${tectonicBinary.absolutePath}\n")
        logBuilder.append("[INFO] Executing Tectonic engine (fully offline)...\n")
        
        try {
            // Use -b to point Tectonic to the local flat bundle directory.
            // Use --only-cached to guarantee zero network access.
            val processBuilder = ProcessBuilder(
                tectonicBinary.absolutePath,
                "-b", bundleDir.absolutePath,
                "--only-cached",
                "document.tex"
            )
            processBuilder.directory(workDir)
            processBuilder.redirectErrorStream(true)

            // Set environment variables for Tectonic's internal operations
            val env = processBuilder.environment()
            env["HOME"] = workDir.absolutePath
            env["XDG_CACHE_HOME"] = workDir.absolutePath
            env["TMPDIR"] = workDir.absolutePath
            
            val process = processBuilder.start()
            
            val reader = BufferedReader(InputStreamReader(process.inputStream))
            var line: String?
            while (reader.readLine().also { line = it } != null) {
                logBuilder.append(line).append("\n")
            }
            
            val exitCode = process.waitFor()
            logBuilder.append("[INFO] Tectonic finished with exit code $exitCode\n")
            
            if (exitCode != 0) {
                val logOutput = logBuilder.toString()
                throw Exception("Tectonic compilation failed with exit code $exitCode.\n\n--- TECTONIC LOG ---\n$logOutput")
            }
            
            if (!pdfFile.exists()) {
                throw Exception("PDF file was not generated by Tectonic.")
            }
            
            return pdfFile
            
        } catch (e: Exception) {
            logBuilder.append("[ERROR] Execution failed: ${e.message}\n")
            throw e
        }
    }
}
