package com.example

import android.content.Context
import android.util.Log
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.util.zip.ZipInputStream

object LocalLatexCompiler {

    fun compile(context: Context, source: String, logBuilder: StringBuilder): File {
        logBuilder.append("[INFO] Starting true offline compilation using native Tectonic engine...\n")
        
        val workDir = context.cacheDir
        val sourceFile = File(workDir, "document.tex")
        val pdfFile = File(workDir, "document.pdf")
        
        // Clean up old pdf
        if (pdfFile.exists()) {
            pdfFile.delete()
        }

        // Write the source tex file
        sourceFile.writeText(source, Charsets.UTF_8)
        logBuilder.append("[INFO] Wrote document.tex to local cache.\n")

        // Pre-warm the Tectonic cache for 100% true offline operation
        val tectonicCacheDir = File(workDir, "Tectonic")
        if (!tectonicCacheDir.exists()) {
            logBuilder.append("[INFO] Pre-warming fully offline LaTeX bundle cache...\n")
            try {
                context.assets.open("tectonic_cache.zip").use { input ->
                    ZipInputStream(input).use { zis ->
                        var entry = zis.nextEntry
                        while (entry != null) {
                            // Extract straight into Tectonic dir since zip contains the inner files/folders of cache
                            val file = File(tectonicCacheDir, entry.name)
                            if (entry.isDirectory) {
                                file.mkdirs()
                            } else {
                                file.parentFile?.mkdirs()
                                file.outputStream().use { zis.copyTo(it) }
                            }
                            entry = zis.nextEntry
                        }
                    }
                }
                logBuilder.append("[INFO] Cache warmed successfully!\n")
            } catch (e: Exception) {
                logBuilder.append("[WARN] Failed to unzip cache: ${e.localizedMessage}\n")
            }
        }
        
        // Locate the Tectonic binary in the native libraries directory
        val nativeLibraryDir = context.applicationInfo.nativeLibraryDir
        val tectonicBinary = File(nativeLibraryDir, "libtectonic.so")
        
        if (!tectonicBinary.exists()) {
            throw Exception("Tectonic binary not found in native library directory at ${tectonicBinary.absolutePath}")
        }
        
        logBuilder.append("[INFO] Located executable Tectonic engine at ${tectonicBinary.absolutePath}\n")
        logBuilder.append("[INFO] Executing Tectonic engine...\n")
        
        try {
            val processBuilder = ProcessBuilder(
                tectonicBinary.absolutePath, 
                "document.tex"
            )
            processBuilder.directory(workDir)
            processBuilder.redirectErrorStream(true)

            // Tectonic strictly requires a writable HOME/XDG_CACHE_HOME to download its format bundle.
            // By setting XDG_CACHE_HOME to workDir, Tectonic will use workDir/Tectonic,
            // which we just pre-warmed from the zip file!
            val env = processBuilder.environment()
            env["HOME"] = workDir.absolutePath
            env["XDG_CACHE_HOME"] = workDir.absolutePath
            env["TMPDIR"] = workDir.absolutePath
            
            val process = processBuilder.start()
            
            val reader = BufferedReader(InputStreamReader(process.inputStream))
            var line: String?
            while (reader.readLine().also { line = it } != null) {
                logBuilder.append(line).append("\n")
            }
            
            val exitCode = process.waitFor()
            logBuilder.append("[INFO] Tectonic finished with exit code $exitCode\n")
            
            if (exitCode != 0) {
                // Return the actual Tectonic output in the exception so the user can see what failed
                val logOutput = logBuilder.toString()
                throw Exception("Tectonic compilation failed with exit code $exitCode.\n\n--- TECTONIC LOG ---\n$logOutput")
            }
            
            if (!pdfFile.exists()) {
                throw Exception("PDF file was not generated by Tectonic.")
            }
            
            return pdfFile
            
        } catch (e: Exception) {
            logBuilder.append("[ERROR] Execution failed: ${e.message}\n")
            throw e
        }
    }
}
